### ISSUE TITLE
可否加个在线保持功能呢？

### ISSUE THREAD

**Issue by 276562578** [frederick-wang/bnu-cernet-cli#1]
通过定时轮训查询在线状态之后掉线重登？

**Comment by 276562578** [comment]
`*/10 * * * * /bin/bash -c 'cd /path/to/bnu-cernet-cli && if [[ -z $(./bnu_cernet status | grep "在线") ]]; then ./bnu_cernet login -u username -p passwd; fi' >> /path/to/bnu-cernet-cli/cron.log 2>&1`
可以在crontab中加入这句

**Comment by frederick-wang** [comment]
收到，感谢反馈。我将其添加到 README 中。
